[package]
name = "bayer-warp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
warp = "0"
tokio = { version = "1", features = [ "full" ] }
serde = { version = "1", features = [ "derive" ] }
tracing = "0"
tracing-subscriber = "0"
